name: picam
channels:
  - nodefaults
  - conda-forge
  - pytorch-nightly
dependencies:
  # Step: Python Main
  - python
  - pip
  - setuptools
  - wheel

  # Step: Common
  - tqdm

  # Step: Science
  - numpy

  # Step: Images
  - pillow

  # Step: Pip
  - pip:
      # !!! ATTENTION !!!
      # I faced that when this file has multiple PIP sections, only the last section is installed.
      # Part: OpenCV
      # Official packages https://pypi.org/project/opencv-python/
      - opencv-python-headless
      #- opencv-contrib-python-headless
      # Part:
      - rpi-libcamera
